# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/david/Desktop/MyGithub/pb11_startracker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/david/Desktop/MyGithub/pb11_startracker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/Desktop/MyGithub/pb11_startracker/CMakeFiles /home/david/Desktop/MyGithub/pb11_startracker/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/Desktop/MyGithub/pb11_startracker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pb11

# Build rule for target.
pb11: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pb11
.PHONY : pb11

# fast build rule for target.
pb11/fast:
	$(MAKE) -f CMakeFiles/pb11.dir/build.make CMakeFiles/pb11.dir/build
.PHONY : pb11/fast

#=============================================================================
# Target rules for targets named run_startracker

# Build rule for target.
run_startracker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_startracker
.PHONY : run_startracker

# fast build rule for target.
run_startracker/fast:
	$(MAKE) -f CMakeFiles/run_startracker.dir/build.make CMakeFiles/run_startracker.dir/build
.PHONY : run_startracker/fast

#=============================================================================
# Target rules for targets named run_standalone

# Build rule for target.
run_standalone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_standalone
.PHONY : run_standalone

# fast build rule for target.
run_standalone/fast:
	$(MAKE) -f CMakeFiles/run_standalone.dir/build.make CMakeFiles/run_standalone.dir/build
.PHONY : run_standalone/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

run_startracker.o: run_startracker.cpp.o

.PHONY : run_startracker.o

# target to build an object file
run_startracker.cpp.o:
	$(MAKE) -f CMakeFiles/run_startracker.dir/build.make CMakeFiles/run_startracker.dir/run_startracker.cpp.o
.PHONY : run_startracker.cpp.o

run_startracker.i: run_startracker.cpp.i

.PHONY : run_startracker.i

# target to preprocess a source file
run_startracker.cpp.i:
	$(MAKE) -f CMakeFiles/run_startracker.dir/build.make CMakeFiles/run_startracker.dir/run_startracker.cpp.i
.PHONY : run_startracker.cpp.i

run_startracker.s: run_startracker.cpp.s

.PHONY : run_startracker.s

# target to generate assembly for a file
run_startracker.cpp.s:
	$(MAKE) -f CMakeFiles/run_startracker.dir/build.make CMakeFiles/run_startracker.dir/run_startracker.cpp.s
.PHONY : run_startracker.cpp.s

star_tracker.o: star_tracker.cpp.o

.PHONY : star_tracker.o

# target to build an object file
star_tracker.cpp.o:
	$(MAKE) -f CMakeFiles/run_startracker.dir/build.make CMakeFiles/run_startracker.dir/star_tracker.cpp.o
.PHONY : star_tracker.cpp.o

star_tracker.i: star_tracker.cpp.i

.PHONY : star_tracker.i

# target to preprocess a source file
star_tracker.cpp.i:
	$(MAKE) -f CMakeFiles/run_startracker.dir/build.make CMakeFiles/run_startracker.dir/star_tracker.cpp.i
.PHONY : star_tracker.cpp.i

star_tracker.s: star_tracker.cpp.s

.PHONY : star_tracker.s

# target to generate assembly for a file
star_tracker.cpp.s:
	$(MAKE) -f CMakeFiles/run_startracker.dir/build.make CMakeFiles/run_startracker.dir/star_tracker.cpp.s
.PHONY : star_tracker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pb11"
	@echo "... run_startracker"
	@echo "... run_standalone"
	@echo "... clean-all"
	@echo "... run_startracker.o"
	@echo "... run_startracker.i"
	@echo "... run_startracker.s"
	@echo "... star_tracker.o"
	@echo "... star_tracker.i"
	@echo "... star_tracker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

